# Generated by Django 4.1.5 on 2023-02-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.CharField(max_length=32)),
                ('updated_on', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
