# Generated by Django 4.1.5 on 2023-02-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField(verbose_name='Choice time')),
                ('remark', models.TextField(null=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bizchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bizquestion')),
            ],
        ),
    ]
